-- MySQL Script generated by MySQL Workbench
-- Sáb 08 Ago 2015 23:33:08 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema laboratorio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema laboratorio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `laboratorio` DEFAULT CHARACTER SET latin1 ;
USE `laboratorio` ;

-- -----------------------------------------------------
-- Table `laboratorio`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laboratorio`.`endereco` (
  `idEndereco` INT NOT NULL,
  `logradouro` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `cep` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `UF` VARCHAR(45) NULL,
  PRIMARY KEY (`idEndereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laboratorio`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laboratorio`.`cliente` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `endereco` INT(11) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `cpf` VARCHAR(45) NULL,
  `sexo` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `login` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_cliente_endereco_idx` (`endereco` ASC),
  CONSTRAINT `fk_cliente_endereco`
    FOREIGN KEY (`endereco`)
    REFERENCES `laboratorio`.`endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `laboratorio`.`tipoExame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laboratorio`.`tipoExame` (
  `codigoTipo` INT NOT NULL,
  `nomeExame` VARCHAR(50) NULL DEFAULT NULL,
  `custo` DOUBLE NULL DEFAULT NULL,
  `horaJenjum` INT(3) NULL DEFAULT NULL,
  `prazoEntrega` INT(3) NULL DEFAULT NULL,
  PRIMARY KEY (`codigoTipo`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `laboratorio`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laboratorio`.`usuario` (
  `matricula` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NULL DEFAULT NULL,
  `login` VARCHAR(50) NULL DEFAULT NULL,
  `senha` VARCHAR(30) NULL DEFAULT NULL,
  `cpf` VARCHAR(45) NULL,
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `laboratorio`.`exame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laboratorio`.`exame` (
  `codigo` INT NOT NULL,
  `codigoTipo` INT NOT NULL,
  `codigoCliente` INT NOT NULL,
  `dataExame` VARCHAR(45) NULL,
  `dataEntrega` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_exame_tipoExame_idx` (`codigoTipo` ASC),
  INDEX `fk_exame_cliente1_idx` (`codigoCliente` ASC),
  CONSTRAINT `fk_exame_tipoExame`
    FOREIGN KEY (`codigoTipo`)
    REFERENCES `laboratorio`.`tipoExame` (`codigoTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exame_cliente1`
    FOREIGN KEY (`codigoCliente`)
    REFERENCES `laboratorio`.`cliente` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
